[project]
name = 'Tokenized-Customer-Data-Platform-Analytics-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.behavior-analysis]
path = 'contracts/behavior-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.journey-mapping]
path = 'contracts/journey-mapping.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
